version: '3.2'

services:
  backend:
    container_name: "backend"
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      - test
    ports:
      - "8080:8080"
    command: bash -c '
      uvicorn main:app --host=0.0.0.0 --port=8080
      '
    depends_on:
      - db

  db:
    container_name: "database"
    image: postgres:12.0-alpine
    volumes:
      - point_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'point'
      POSTGRES_PASSWORD: 'point'
      POSTGRES_DB: 'point'
    networks:
      - test
    expose:
      - 5438
    ports:
      - "5438:5438"
    command:
      - "postgres"
      - "-c"
      - "port=5438"

volumes:
  point_data:
